version: '3.9'

services:
  postgres:
    image: postgres:13.21-alpine3.21
    container_name: threadspire-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: threadspire
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: